name: Update Contribution Calendar

on:
  schedule:
    - cron: "0 */12 * * *"

  workflow_dispatch:


jobs:

  update:

    runs-on: ubuntu-latest


    steps:

    - name: Checkout
      uses: actions/checkout@v4


    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20


    - name: Generate Calendar
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

      run: |
        node scripts/generate-calendar.js


    - name: Commit SVG

      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

        git add assets/contribution.svg

        git commit -m "Update contribution calendar" || exit 0

        git push
